apiVersion: apps/v1
kind: Deployment
metadata:
  name: tothemoon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tothemoon
  template:
    metadata:
      labels:
        app: tothemoon
    spec:
      containers:
      - name: tothemoon
        image: tristanpostley/tothemoon
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: tothemoon
spec:
  ports:
  - port: 6379
  selector:
    app: tothemoon