apiVersion: apps/v1
kind: Deployment
metadata:
  name: tothemoon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tothemoon
  template:
    metadata:
      labels:
        app: tothemoon
    spec:
      nodeSelector:
          "kubernetes.io/os": linux
      terminationGracePeriodSeconds: 30
      containers:
      - name: tothemoon
        image: tristanpostley/tothemoon-post:3
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: tothemoon-post
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: tothemoon-post